@startuml unassign-group/GroupUnassignSequenceDiagram /' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant ":UnassignGroupCommandParser" as UnassignGroupCommandParser LOGIC_COLOR
participant "c:UnassignGroupCommand" as UnassignGroupCommand LOGIC_COLOR
end box

[-> LogicManager : execute("grpunassign /n Alex /g Students")
activate LogicManager

LogicManager -> HitListParser : parseCommand("grpunassign /n Alex /g Students")
activate HitListParser

create UnassignGroupCommandParser
HitListParser -> UnassignGroupCommandParser
activate UnassignGroupCommandParser
UnassignGroupCommandParser --> HitListParser
deactivate UnassignGroupCommandParser

HitListParser -> UnassignGroupCommandParser : parse(" /n Alex /g Students")
activate UnassignGroupCommandParser

create UnassignGroupCommand
UnassignGroupCommandParser -> UnassignGroupCommand
activate UnassignGroupCommand
UnassignGroupCommand --> UnassignGroupCommandParser : c
deactivate UnassignGroupCommand

UnassignGroupCommandParser --> HitListParser : c
deactivate UnassignGroupCommandParser
destroy UnassignGroupCommandParser

HitListParser --> LogicManager : c
deactivate HitListParser

@enduml
