@startuml storage-class-diagram /' Renames the file to kebab-case when exported as an image.'/
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "HitList Storage" #F4F6F6{
Class "<<interface>>\nHitListStorage" as HitListStorage
Class JsonHitListStorage
Class JsonSerializableHitList
Class JsonAdaptedPerson
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" HitListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> HitListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHitListStorage .up.|> HitListStorage
JsonHitListStorage ..> JsonSerializableHitList
JsonSerializableHitList --> "*" JsonAdaptedPerson

@enduml
