@startuml assign-group/GroupAssignSequenceDiagram
/' Renames the file to kebab-case when exported as an image.'/
!include ../style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HitListParser" as HitListParser LOGIC_COLOR
participant ":AssignGroupCommandParser" as AssignGroupCommandParser LOGIC_COLOR
participant "c:AssignGroupCommand" as AssignGroupCommand LOGIC_COLOR
end box

[-> LogicManager : execute("grpassign /n Alex /g Students")
activate LogicManager

LogicManager -> HitListParser : parseCommand("grpassign /n Alex /g Students")
activate HitListParser

create AssignGroupCommandParser
HitListParser -> AssignGroupCommandParser
activate AssignGroupCommandParser
AssignGroupCommandParser --> HitListParser
deactivate AssignGroupCommandParser

HitListParser -> AssignGroupCommandParser : parse(" /n Alex /g Students")
activate AssignGroupCommandParser

create AssignGroupCommand
AssignGroupCommandParser -> AssignGroupCommand
activate AssignGroupCommand
AssignGroupCommand --> AssignGroupCommandParser : c
deactivate AssignGroupCommand

AssignGroupCommandParser --> HitListParser : c
deactivate AssignGroupCommandParser

AssignGroupCommandParser -[hidden]-> HitListParser
destroy AssignGroupCommandParser

HitListParser --> LogicManager : c
deactivate HitListParser

[<--LogicManager : c
deactivate LogicManager
@enduml